import {
  loginController,
  registerController,
  homeController,
  clientsController,
  createClientController,
  profileClientController,
  createPetController,
  petsController,
  profilePetController,
  treatmentController,
  createAntecedentController,
  createTreatmentController,
  createMedicamentController,
  inventoryController,
  createProductController,
  createProductTypeController,
  createBreedController,
  createSpecieController,
  profileSpecieController,
  editSpecieController,
  profileProductTypeController,
  editProductTypeController,
  createServiceController,
  servicesController,
  administrationController,
  editBreedController,
  profileBreedController,
  editServiceController,
  createMedicamentInventoryController,
  createMedicamentInfoController,
} from "../views/index";

export const routes = {
  inicio: {
    path: "home/index.html",
    controller: homeController,
    private: true,
    layout: "mainLayout.html",
    slot: "main",
  },
  clientes: {
    "/": {
      path: "clients/index.html",
      controller: clientsController,
      private: true,
      layout: "mainLayout.html",
      slot: "main",
    },
    crear: {
      path: "clients/create/index.html",
      controller: createClientController,
      private: true,
      addHtml: true,
    },
    editar: {
      path: "clients/edit/index.html",
      controller: () => {},
      private: true,
      addHtml: true,
    },
    perfil: {
      path: "clients/profile/index.html",
      controller: profileClientController,
      private: true,
      addHtml: true,
    },
  },
  mascotas: {
    "/": {
      path: "pets/index.html",
      controller: petsController,
      private: true,
      layout: "mainLayout.html",
      slot: "main",
    },
    crear: {
      path: "pets/create/index.html",
      controller: createPetController,
      private: true,
      addHtml: true,
    },
    editar: {
      path: "pets/edit/index.html",
      controller: () => {},
      private: true,
      addHtml: true,
    },
    perfil: {
      path: "pets/profile/index.html",
      controller: profilePetController,
      private: true,
      layout: "mainLayout.html",
      slot: "main",
    },
  },
  antecedente: {
    crear: {
      path: "antecedent/create/index.html",
      controller: createAntecedentController,
      private: true,
      addHtml: true,
    },
    tratamiento: {
      path: "antecedent/treatment/index.html",
      controller: treatmentController,
      private: true,
      addHtml: true,
    },
    tratamientoCrear: {
      path: "antecedent/treatment/create/index.html",
      controller: createTreatmentController,
      private: true,
      addHtml: true,
    },
    medicamento: {
      path: "antecedent/treatment/medicament/create/index.html",
      controller: createMedicamentController,
      private: true,
      addHtml: true,
    },
  },
  administrar_datos: {
    "/": {
      path: "administration/index.html",
      controller: administrationController,
      private: true,
      layout: "mainLayout.html",
      slot: "main",
    },
    especiesCrear: {
      path: "administration/species/create/index.html",
      controller: createSpecieController,
      private: true,
      addHtml: true,
    },
    razasCrear: {
      path: "administration/breeds/create/index.html",
      controller: createBreedController,
      private: true,
      addHtml: true,
    },
    tipos_productosCrear: {
      path: "administration/productsTypes/create/index.html",
      controller: createProductTypeController,
      private: true,
      addHtml: true,
    },
    especiesPerfil: {
      path: "administration/species/profile/index.html",
      controller: profileSpecieController,
      private: true,
      addHtml: true,
    },
    razasPerfil: {
      path: "administration/breeds/profile/index.html",
      controller: profileBreedController,
      private: true,
      addHtml: true,
    },
    tipos_productosPerfil: {
      path: "administration/productsTypes/profile/index.html",
      controller: profileProductTypeController,
      private: true,
      addHtml: true,
    },
    especiesEditar: {
      path: "administration/species/edit/index.html",
      controller: editSpecieController,
      private: true,
      addHtml: true,
    },
    razasEditar: {
      path: "administration/breeds/edit/index.html",
      controller: editBreedController,
      private: true,
      addHtml: true,
    },
    tipos_productosEditar: {
      path: "administration/productsTypes/edit/index.html",
      controller: editProductTypeController,
      private: true,
      addHtml: true,
    },
  },
  servicios: {
    "/": {
      path: "services/index.html",
      controller: servicesController,
      private: true,
      layout: "mainLayout.html",
      slot: "main",
    },
    crear: {
      path: "services/create/index.html",
      controller: createServiceController,
      private: true,
      addHtml: true,
    },
    editar: {
      path: "services/edit/index.html",
      controller: editServiceController,
      private: true,
      addHtml: true,
    },
  },
  inventario: {
    "/": {
      path: "inventory/index.html",
      controller: inventoryController,
      private: true,
      layout: "mainLayout.html",
      slot: "main",
    },
    productosCrear: {
      path: "inventory/products/create/index.html",
      controller: createProductController,
      private: true,
      addHtml: true,
    },
    productosPerfil: {
      path: "inventory/products/profile/index.html",
      controller: () => {},
      private: true,
      addHtml: true,
    },
    medicamentosCrear: {
      path: "inventory/medicaments/create/index.html",
      controller: createMedicamentInventoryController,
      private: true,
      addHtml: true,
    },
    medicamentosPerfil: {
      path: "inventory/products/profile/index.html",
      controller: () => {},
      private: true,
      addHtml: true,
    },
  },
  medicamentos_info: {
    crear: {
      path: "medicaments/create/index.html",
      controller: createMedicamentInfoController,
      private: true,
      addHtml: true,
    },
    perfil: {
      path: "inventory/products/profile/index.html",
      controller: () => {},
      private: true,
      addHtml: true,
    },
  },
  login: {
    path: "auth/login/index.html",
    controller: loginController,
    private: false,
  },
  registro: {
    path: "auth/register/index.html",
    controller: registerController,
    private: false,
  },
};
