import {
  loginController,
  homeController,
  clientsController,
  createClientController,
  profileClientController,
  createPetController,
  petsController,
  profilePetController,
  treatmentController,
  createAntecedentController,
  createTreatmentController,
  createMedicamentController,
  inventoryController,
  createProductController,
  createProductTypeController,
  createBreedController,
  createSpecieController,
  profileSpecieController,
  editSpecieController,
  profileProductTypeController,
  editProductTypeController,
  createServiceController,
  servicesController,
  administrationController,
  editBreedController,
  profileBreedController,
  editServiceController,
  createMedicamentInventoryController,
  createMedicamentInfoController,
  editMedicamentInfoController,
  medicamentsController,
  personalController,
  createPersonalController,
  createPersonalExistController,
  profilePersonalController,
  editPersonalController,
  editClientController,
  createClienteExistController,
  resumeController,
  createDetailsController,
  createVentaController,
  ventasController,
  editVentaController,
  editMedicamentInventoryController,
  profileVentaController,
  editPetController,
  editAntecedentController,
  editTreatmentController,
  editMedicamentTreatmentController,
  editProductController,
  profileMedicamentInfoController,
} from "../views/index";

export const routes = {
  inicio: {
    path: "home/index.html",
    controller: homeController,
    private: true,
    needLayout: true,
    slot: "main",
  },
  clientes: {
    "/": {
      path: "clients/index.html",
      controller: clientsController,
      private: true,
      needLayout: true,
      slot: "main",
      can: ["usuario.view", "usuario.view-client"],
    },
    crear: {
      path: "clients/create/index.html",
      controller: createClientController,
      private: true,
      addHtml: true,
      can: ["usuario.create-client"],
    },
    crearExistente: {
      path: "clients/createExist/index.html",
      controller: createClienteExistController,
      private: true,
      addHtml: true,
      can: ["usuario.create-client"],
    },
    perfil: {
      "/": {
        path: "clients/profile/index.html",
        controller: profileClientController,
        private: true,
        addHtml: true,
        can: ["usuario.view"],
      },
      editar: {
        path: "clients/edit/index.html",
        controller: editClientController,
        private: true,
        addHtml: true,
        can: ["usuario.update-client"],
      },
      mascotas: {
        crear: {
          path: "pets/create/index.html",
          controller: createPetController,
          private: true,
          addHtml: true,
          can: ["mascota.create"],
        },
      },
    },
  },
  mascotas: {
    "/": {
      path: "pets/index.html",
      controller: petsController,
      private: true,
      needLayout: true,
      slot: "main",
      can: ["mascota.view"],
    },
    crear: {
      path: "pets/create/index.html",
      controller: createPetController,
      private: true,
      addHtml: true,
      can: ["mascota.create"],
    },
    perfil: {
      "/": {
        path: "pets/profile/index.html",
        controller: profilePetController,
        private: true,
        needLayout: true,
        slot: "main",
        can: ["mascota.view"],
      },
      editar: {
        path: "pets/edit/index.html",
        controller: editPetController,
        private: true,
        addHtml: true,
        can: ["mascota.update"],
      },
      antecedente: {
        crear: {
          path: "antecedent/create/index.html",
          controller: createAntecedentController,
          private: true,
          addHtml: true,
          can: ["antecedente.create"],
        },
        editar: {
          path: "antecedent/edit/index.html",
          controller: editAntecedentController,
          private: true,
          addHtml: true,
          can: ["antecedente.update"],
        },
        tratamiento: {
          perfil: {
            "/": {
              path: "antecedent/treatment/index.html",
              controller: treatmentController,
              private: true,
              addHtml: true,
              can: ["tratamiento.view"],
            },
            editar: {
              path: "antecedent/treatment/edit/index.html",
              controller: editTreatmentController,
              private: true,
              addHtml: true,
              can: ["tratamiento.update"],
            },
            medicamento: {
              crear: {
                path: "antecedent/treatment/medicament/create/index.html",
                controller: createMedicamentController,
                private: true,
                addHtml: true,
                can: ["medicamento-tratamiento.create"],
              },
              editar: {
                path: "antecedent/treatment/medicament/edit/index.html",
                controller: editMedicamentTreatmentController,
                private: true,
                addHtml: true,
                can: ["medicamento-tratamiento.update"],
              },
            },
          },
          crear: {
            path: "antecedent/treatment/create/index.html",
            controller: createTreatmentController,
            private: true,
            addHtml: true,
            can: ["tratamiento.create"],
          },
        },
      },
    },
  },

  "administrar-datos": {
    "/": {
      path: "administration/index.html",
      controller: administrationController,
      private: true,
      needLayout: true,
      slot: "main",
      can: ["especie.view"],
    },
    especies: {
      razas: {
        crear: {
          path: "administration/breeds/create/index.html",
          controller: createBreedController,
          private: true,
          addHtml: true,
          can: ["raza.create"],
        },
        perfil: {
          "/": {
            path: "administration/breeds/profile/index.html",
            controller: profileBreedController,
            private: true,
            addHtml: true,
            can: ["raza.view"],
          },
          editar: {
            path: "administration/breeds/edit/index.html",
            controller: editBreedController,
            private: true,
            addHtml: true,
            can: ["raza.update"],
          },
        },
      },
      crear: {
        path: "administration/species/create/index.html",
        controller: createSpecieController,
        private: true,
        addHtml: true,
        can: ["especie.create"],
      },
      perfil: {
        "/": {
          path: "administration/species/profile/index.html",
          controller: profileSpecieController,
          private: true,
          addHtml: true,
          can: ["especie.view"],
        },
        editar: {
          path: "administration/species/edit/index.html",
          controller: editSpecieController,
          private: true,
          addHtml: true,
          can: ["especie.update"],
        },
      },
    },
    "tipos-productos": {
      crear: {
        path: "administration/productsTypes/create/index.html",
        controller: createProductTypeController,
        private: true,
        addHtml: true,
        can: ["tipo-producto.create"],
      },
      perfil: {
        "/": {
          path: "administration/productsTypes/profile/index.html",
          controller: profileProductTypeController,
          private: true,
          addHtml: true,
          can: ["tipo-producto.view"],
        },
        editar: {
          path: "administration/productsTypes/edit/index.html",
          controller: editProductTypeController,
          private: true,
          addHtml: true,
          can: ["tipo-producto.update"],
        },
      },
    },
  },
  servicios: {
    "/": {
      path: "services/index.html",
      controller: servicesController,
      private: true,
      needLayout: true,
      slot: "main",
      can: ["servicio.view"],
    },
    crear: {
      path: "services/create/index.html",
      controller: createServiceController,
      private: true,
      addHtml: true,
      can: ["servicio.create"],
    },
    editar: {
      path: "services/edit/index.html",
      controller: editServiceController,
      private: true,
      addHtml: true,
      can: ["servicio.update"],
    },
  },
  inventario: {
    "/": {
      path: "inventory/index.html",
      controller: inventoryController,
      private: true,
      needLayout: true,
      slot: "main",
      can: ["producto.view"],
    },
    productos: {
      crear: {
        path: "inventory/products/create/index.html",
        controller: createProductController,
        private: true,
        addHtml: true,
        can: ["producto.create"],
      },
      editar: {
        path: "inventory/products/edit/index.html",
        controller: editProductController,
        private: true,
        addHtml: true,
        can: ["producto.update"],
      },
    },
    medicamentos: {
      crear: {
        "/": {
          path: "inventory/medicaments/create/index.html",
          controller: createMedicamentInventoryController,
          private: true,
          addHtml: true,

          can: ["medicamento.create"],
        },
        "info-medicamentos": {
          crear: {
            path: "medicaments/create/index.html",
            controller: createMedicamentInfoController,
            private: true,
            addHtml: true,
            can: ["info-medicamento.create"],
          },
        },
      },
      editar: {
        path: "inventory/medicaments/edit/index.html",
        controller: editMedicamentInventoryController,
        private: true,
        addHtml: true,
        can: ["medicamento.update"],
      },
    },
  },
  "info-medicamentos": {
    "/": {
      path: "medicaments/index.html",
      controller: medicamentsController,
      private: true,
      needLayout: true,
      slot: "main",
      can: ["info-medicamento.view"],
    },
    crear: {
      path: "medicaments/create/index.html",
      controller: createMedicamentInfoController,
      private: true,
      addHtml: true,
      can: ["info-medicamento.create"],
    },
    perfil: {
      "/": {
        path: "medicaments/profile/index.html",
        controller: profileMedicamentInfoController,
        private: true,
        addHtml: true,
        can: ["info-medicamento.view"],
      },
      editar: {
        path: "medicaments/edit/index.html",
        controller: editMedicamentInfoController,
        private: true,
        addHtml: true,
        can: ["info-medicamento.update"],
      },
    },
  },
  login: {
    path: "auth/login/index.html",
    controller: loginController,
    private: false,
  },
  usuarios: {
    "/": {
      path: "personal/index.html",
      controller: personalController,
      private: true,
      needLayout: true,
      slot: "main",
      can: ["usuario.view"],
    },
    crear: {
      path: "personal/create/index.html",
      controller: createPersonalController,
      private: false,
      needLayout: true,
      slot: "main",
      can: ["usuario.create-personal"],
    },
    crearExistente: {
      path: "personal/createExist/index.html",
      controller: createPersonalExistController,
      private: false,
      addHtml: true,
      can: ["usuario.create-personal"],
    },
    perfil: {
      "/": {
        path: "personal/profile/index.html",
        controller: profilePersonalController,
        private: true,
        addHtml: true,
        can: ["usuario.view"],
      },
      editar: {
        path: "personal/edit/index.html",
        controller: editPersonalController,
        private: true,
        addHtml: true,

        can: ["usuario.update"],
      },
    },
  },

  ventas: {
    "/": {
      path: "ventas/index.html",
      controller: ventasController,
      private: true,
      needLayout: true,
      slot: "main",
      can: ["venta.view"],
    },
    crear: {
      "/": {
        path: "ventas/create/index.html",
        controller: createVentaController,
        private: false,
        needLayout: true,
        slot: "main",
        can: ["venta.create"],
      },
      "agregar-elemento": {
        path: "ventas/details/create/index.html",
        controller: createDetailsController,
        private: false,

        addHtml: true,
        can: ["venta.create"],
      },
      finalizar: {
        path: "ventas/resume/index.html",
        controller: resumeController,
        private: true,
        addHtml: true,
        can: ["venta.create"],
      },
    },
    perfil: {
      "/": {
        path: "ventas/profile/index.html",
        controller: profileVentaController,
        private: true,
        needLayout: true,

        can: ["venta.view"],
      },
      editar: {
        path: "ventas/edit/index.html",
        controller: editVentaController,
        private: true,
        addHtml: true,
        can: ["venta.update"],
      },
    },
  },
};
